version: 2

jobs:
  build:
    docker:
      - image: node:9-alpine
    steps:
      - run:
          name: Installing system dependencies
          command: |
            apk add --no-progress --update ca-certificates openssl git openssh
            update-ca-certificates

      - checkout

      - run:
          name: Install dependencies
          command: |
            npm install --no-optional --silent

      - run:
          name: Lint code
          command: |
            mkdir ~/reports
            node_modules/.bin/eslint --format junit --output-file ~/reports/eslint/report.xml src/server

      - store_test_results:
          path: ~/reports

      - store_artifacts:
          path: ~/reports
